### ISSUE TITLE
Add W20 Smart Table components

### ISSUE THREAD

**Issue by evinel** [seedstack/w20-components#8]
Smart Tables is angular html table module.
documentation : http://lorenzofox3.github.io/smart-table-website/

**Comment by adrienlauer** [comment]
I don't think there is much to do as this is purely a native AngularJS component. I don't see any configuration nor any specific integration to do in order to use it with W20, it should work out of the box.

@evinel : do you have some specific idea in mind ? something that would bring additional value over the plain library ?

**Comment by evinel** [comment]
Great! It's work. You can close this issue. 

@adrienlauer I contact you by mail or irc to explain my project with w20.

**Comment by adrienlauer** [comment]
@evinel Come talking on the #seedstack-talk channel when you want. I'm a bit curious about what you're doing with W20.
